# AMAZON AIR CONDITIONERS SALES ANALYSIS

### Importing Packages

In [299]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Reading Data

In [300]:
Ac_data=pd.read_csv("Air Conditioners.csv")
Ac_data

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790"
...,...,...,...,...,...,...,...,...,...
715,Personal Air Conditioners Portable AC Mini Air...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71RkCzQZyd...,https://www.amazon.in/Personal-Conditioners-Po...,NaN,NaN,"₹10,234","₹13,999"
716,Air Conditioner Fan Personal Desk Fan Space Ai...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/719ujjLfw7...,https://www.amazon.in/Conditioner-Personal-Eva...,NaN,NaN,NaN,"₹9,881"
717,"Portable Air Conditioners, Personal Air Condit...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/71l59r1G-J...,https://www.amazon.in/Portable-Conditioners-Pe...,NaN,NaN,NaN,"₹6,361"
718,"Portable Air Conditioner Fan, Personal Air Coo...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/61GXC1nOlS...,https://www.amazon.in/Portable-Conditioner-Per...,2.8,207,NaN,"₹7,671"
719,Air Choice Desktop Protable AC Cooler Fan For ...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71yqMTaaWT...,https://www.amazon.in/Air-Choice-Desktop-Prota...,2.5,296,NaN,"₹8,592"

### Checking Null Values

In [301]:
Ac_data.isnull().sum()

name                0
main_category       0
sub_category        0
image               0
link                0
ratings           287
no_of_ratings     287
discount_price    263
actual_price      220
dtype: int64

### Checking Data Types

In [302]:
Ac_data.dtypes

name              object
main_category     object
sub_category      object
image             object
link              object
ratings           object
no_of_ratings     object
discount_price    object
actual_price      object
dtype: object

### Checking Any Duplicate Rows In Data

In [303]:
Ac_data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
715    False
716    False
717    False
718    False
719    False
Length: 720, dtype: bool

### Converting categorical data into numeric

#### I have found a "Get" value in the ratings column which is representing '0' as it has no ratings till now.

In [304]:
Ac_data[Ac_data['ratings']=='Get']

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
437,Daikin 1.8 Ton 3 Star Inverter Split Ac (Coppe...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51hn7NHS3T...,https://www.amazon.in/Daikin-Inverter-Copper-F...,Get,Only 2 left in stock.,"₹59,979","₹72,900"
473,Master Electronic provides Window AC 3-Star 1....,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41B0LWORAr...,https://www.amazon.in/Master-Electronic-provid...,Get,Only 1 left in stock.,"₹36,999","₹39,999"
474,Master Electronic provides 1.5 Ton 3 Star Dust...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/61yVE5P7FU...,https://www.amazon.in/Master-Electronic-provid...,Get,Only 1 left in stock.,"₹36,999","₹39,666"
475,Master Electronics Provides 1 Ton 3 Star Inver...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/11mMBc5fl2...,https://www.amazon.in/Master-Electronics-Provi...,Get,Only 1 left in stock.,"₹46,999","₹49,666"
488,"1.5 Ton 5 Star Inverter Split AC, White",appliances,Air Conditioners,https://m.media-amazon.com/images/I/11au-UO4sB...,https://www.amazon.in/1-5-Star-Inverter-Split-...,Get,Only 2 left in stock.,"₹45,000","₹50,000"
499,SUHANA snow falls Best 5 Star 1.5 Ton Air Cond...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31QQZehTYc...,https://www.amazon.in/SUHANA-snow-falls-Condit...,Get,Only 1 left in stock.,"₹40,000","₹55,956"
582,MEGACOOL CENTRE-Dakin 1.5 Ton 3 Star Fixed Spe...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/21pJ7D2fWm...,https://www.amazon.in/MEGACOOL-CENTRE-Dakin-Fi...,Get,Only 1 left in stock.,"₹65,000","₹1,30,000"
595,Heavy Duty Air Conditioner Outdoor Ac stand,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51mvmI9NjU...,https://www.amazon.in/Heavy-Duty-Conditioner-O...,Get,Only 2 left in stock.,₹899,"₹1,750"
639,Blue Star 1.5 Tr 3 Star Fixed Speed Split AC (...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31Tci462W1...,https://www.amazon.in/Blue-Star-Fixed-Copper-F...,Get,Only 1 left in stock.,"₹39,990","₹52,500"
643,Daikin 1.8 Ton 3 Star Inverter Split AC (Coppe...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/61+ky9zVBZ...,https://www.amazon.in/Daikin-Inverter-Split-Co...,Get,Only 1 left in stock.,"₹54,590","₹72,900"

In [305]:
Ac_data[Ac_data['ratings']=='Get']["ratings"].shape

(10,)

In [306]:
Ac_data["ratings"].replace('Get','0',inplace=True)

In [307]:
Ac_data[Ac_data['ratings']=='Get']["ratings"].shape

(0,)

## Removing special Characters from the numerical data

In [308]:
Ac_data[["discountprice","actualprice"]]=Ac_data[["discount_price","actual_price"]].replace(["₹",","],"",regex=True)
Ac_data[["Ratings","No_of_ratings"]]=Ac_data[["ratings","no_of_ratings"]].replace(["₹",","],"",regex=True)

In [309]:
Ac_data

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price,discountprice,actualprice,Ratings,No_of_ratings
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990",32999,58990,4.2,2255
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990",46490,75990,4.2,2948
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990",34490,61990,4.2,1206
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990",37990,68990,4.0,69
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790",34490,67790,4.1,630
...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,Personal Air Conditioners Portable AC Mini Air...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71RkCzQZyd...,https://www.amazon.in/Personal-Conditioners-Po...,NaN,NaN,"₹10,234","₹13,999",10234,13999,NaN,NaN
716,Air Conditioner Fan Personal Desk Fan Space Ai...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/719ujjLfw7...,https://www.amazon.in/Conditioner-Personal-Eva...,NaN,NaN,NaN,"₹9,881",NaN,9881,NaN,NaN
717,"Portable Air Conditioners, Personal Air Condit...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/71l59r1G-J...,https://www.amazon.in/Portable-Conditioners-Pe...,NaN,NaN,NaN,"₹6,361",NaN,6361,NaN,NaN
718,"Portable Air Conditioner Fan, Personal Air Coo...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/61GXC1nOlS...,https://www.amazon.in/Portable-Conditioner-Per...,2.8,207,NaN,"₹7,671",NaN,7671,2.8,207
719,Air Choice Desktop Protable AC Cooler Fan For ...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71yqMTaaWT...,https://www.amazon.in/Air-Choice-Desktop-Prota...,2.5,296,NaN,"₹8,592",NaN,8592,2.5,296

In [310]:
Ac_data.drop(["image","link","discount_price","actual_price","ratings","no_of_ratings"],axis=1,inplace=True)

### Replacing Null values with median values

In [311]:
Ac_data['No_of_ratings'].replace(['Only 2 left in stock.','Only 1 left in stock.'],['0','1'],inplace=True)

In [312]:
Ac_data["No_of_ratings"].unique()

array(['2255', '2948', '1206', '69', '630', '1666', '1097', '1494', '674',
       '801', '558', '730', '5073', '568', '3670', '312', '88', '432',
       '268', '2', '700', '540', '258', '2178', nan, '1444', '360', '38',
       '1208', '341', '3', '15', '925', '3604', '42', '22', '94', '1866',
       '292', '1830', '8', '536', '201', '2722', '202', '23', '1195', '5',
       '66', '474', '502', '686', '1183', '56', '1', '49', '212', '79',
       '468', '317', '45', '142', '451', '145', '265', '3157', '274',
       '39', '178', '655', '81', '43', '234', '134', '97', '229', '12',
       '748', '926', '62', '14', '440', '85', '260', '118', '172', '387',
       '195', '7', '158', '9', '10', '1295', '16', '303', '120', '55',
       '27', '34', '37', '1573', '29', '6', '112', '200', '11', '121',
       '886', '209', '4', '207', '622', '31', '192', '40', '101', '96',
       '70', '259', '1400', '288', '13', '51', '175', '114', '567', '187',
       '21', '1832', '563', '24', '769', '542', '297', '329', '20', '156',
       '26', '485', '9577', '302', '255', '1420', '169', '3562', '224',
       '25', '449', '218', '913', '373', '776', '60', '54', '19', '74',
       '17', '213', '430', '591', '247', '41', '222', '71', '290', '65',
       '18', '32', '130', '416', '64', '119', '59', '68', '36', '164',
       '77', '47', '98', '0', '581', '398', '774', '232', '44', '50',
       '296'], dtype=object)

In [313]:
Ac_data["discountprice"].fillna(Ac_data["discountprice"].median(),inplace=True)
Ac_data["actualprice"].fillna(Ac_data["actualprice"].median(),inplace=True)
Ac_data["Ratings"].fillna(Ac_data["Ratings"].median(),inplace=True)
Ac_data["No_of_ratings"].fillna(Ac_data["No_of_ratings"].median(),inplace=True)

In [314]:
Ac_data[["discountprice","actualprice","Ratings","No_of_ratings"]].isnull().sum()

discountprice    0
actualprice      0
Ratings          0
No_of_ratings    0
dtype: int64

### Data type conversion from categorical to numerical

In [315]:
Ac_data["discountprice"]= pd.to_numeric(Ac_data["discountprice"])
Ac_data["actualprice"]= pd.to_numeric(Ac_data["actualprice"])
Ac_data["Ratings"]= pd.to_numeric(Ac_data["Ratings"])
Ac_data["No_of_ratings"]= pd.to_numeric(Ac_data["No_of_ratings"])

In [316]:
Ac_data.dtypes

name              object
main_category     object
sub_category      object
discountprice    float64
actualprice      float64
Ratings          float64
No_of_ratings    float64
dtype: object

In [317]:
Ac_data

,name,main_category,sub_category,discountprice,actualprice,Ratings,No_of_ratings
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,32999.0,58990.0,4.2,2255.0
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,46490.0,75990.0,4.2,2948.0
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,34490.0,61990.0,4.2,1206.0
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,37990.0,68990.0,4.0,69.0
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,34490.0,67790.0,4.1,630.0
...,...,...,...,...,...,...,...
715,Personal Air Conditioners Portable AC Mini Air...,appliances,Air Conditioners,10234.0,13999.0,4.0,18.0
716,Air Conditioner Fan Personal Desk Fan Space Ai...,appliances,Air Conditioners,39190.0,9881.0,4.0,18.0
717,"Portable Air Conditioners, Personal Air Condit...",appliances,Air Conditioners,39190.0,6361.0,4.0,18.0
718,"Portable Air Conditioner Fan, Personal Air Coo...",appliances,Air Conditioners,39190.0,7671.0,2.8,207.0
719,Air Choice Desktop Protable AC Cooler Fan For ...,appliances,Air Conditioners,39190.0,8592.0,2.5,296.0

### Basic Exploratory Data Analysis

In [318]:
Ac_data.describe(include='all')

,name,main_category,sub_category,discountprice,actualprice,Ratings,No_of_ratings
count,720,720,720,720.000000,720.000000,720.000000,720.000000
unique,708,1,1,NaN,NaN,NaN,NaN
top,Samsung 1.5 Ton 3 Star Wind-Free Technology In...,appliances,Air Conditioners,NaN,NaN,NaN,NaN
freq,3,720,720,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,40183.979167,55479.741139,3.832639,151.254167
std,NaN,NaN,NaN,11938.526137,18984.776512,0.762711,562.515234
min,NaN,NaN,NaN,199.000000,499.000000,0.000000,0.000000
25%,NaN,NaN,NaN,37282.500000,51472.500000,3.900000,8.000000
50%,NaN,NaN,NaN,39190.000000,56990.000000,4.000000,18.000000
75%,NaN,NaN,NaN,41999.250000,61990.000000,4.000000,40.000000
max,NaN,NaN,NaN,128800.000000,149000.000000,5.000000,9577.000000

# Univariate Questions

### Best Rating Product

In [319]:
print(Ac_data['name'][Ac_data['Ratings'].idxmax()]+ " has Best Rating of "+ str(Ac_data['Ratings'][Ac_data['Ratings'].idxmax()])+" Stars")

Hitachi Split Ac - 1.5 Ton Kiyora 5200Fx I Fresh Inverter - R32 - RSRG518FFEO (Gold) has Best Rating of 5.0 Stars

### Least Rating Product

In [320]:
print(Ac_data['name'][Ac_data['Ratings'].idxmin()]+ " has least Rating of "+ str(Ac_data['Ratings'][Ac_data['Ratings'].idxmin()])+" Stars")

Daikin 1.8 Ton 3 Star Inverter Split Ac (Copper, FTKL/RKL-60TV16U, White, Made In India) has least Rating of 0.0 Stars

### Highest Product

In [321]:
print(Ac_data['name'][Ac_data['discountprice'].idxmax()]+ " has highest price of "+ str(Ac_data['discountprice'][Ac_data['discountprice'].idxmax()])+" Rupees")

Voltas 3Ph Scroll SAC C2-NVenture I-Cassette AC (4 Ton White) has highest price of 128800.0 Rupees

### Cheapest Product

In [322]:
print(Ac_data['name'][Ac_data['discountprice'].idxmin()]+ " has least price of "+ str(Ac_data['discountprice'][Ac_data['discountprice'].idxmin()])+" Rupees")

RISARYA H20R1203 IGBT 1PCS POWER TRANSISTOR 20A 1200V REVERSE CONDUCTING HEATING AND WIDELY USED IN INDUCTION COOKER T0247... has least price of 199.0 Rupees